### ISSUE TITLE
機能設計

### ISSUE THREAD

**Issue by tkcolorado** [takahirosawamura/pinder#1]
<機能調整>
-Modelを調整。SQLのインプット。(modelの組み方を改めて考える。)
-Controller/Rooting/Viewの調整
-サイト内検索機能(タグで管理) 実装する。
-REST API    
-通知機能  
-メッセージ機能  (rails5 のActioncableとかを試す) 
-RSSフィード (builderとかを使う)
-Rspec  (テストフレームワーク)
-gravatorの画像変更 (プロフィール画像の変更)
-ホーム画面のレイアウトの調整 (scssを調整する。) 
<レイアウト調整> 
-edit profileのところでprofile画像を変更できるようにする。
-layoutをchangeからボタンに変更する。
-UI/UXを考える。デザインと文字表記の調整。
-Login前のtop pageのレイアウト調整とrootingの調整。()

-読み物を読み込む (UI/UX/デザイン)

**Comment by takahirosawamura** [comment]
付属したい機能に関しての要素分析と作るサービスの設計を考える。

**Comment by takahirosawamura** [comment]
-edit profileのところでprofile画像を変更できるようにする。
-layoutをchangeからボタンに変更する。
-Controller/Rooting/Viewの調整
-Modelを調整。SQLのインプット。
-UI/UXを考える。デザインと文字表記の調整。
-Login前のtop pageのレイアウト調整とrootingの調整。
